#define ___ int
#define _______ ;
#define _____ =
#define _____________ return
#define __ {
#define _______________ }
#define _ test
#define __________ ==
#define ________ if
#define _________ (
#define ____________ )
#define ___________ 0
#define ______________ 1
#define ______ 3
#define ____ i
