#!/bin/bash
#simple bash script that tests test1, and test2 then tests both files in the same command line
#Eventually i *might* make it test all possible subsets of each testnumber
#and able to work out for itself how many test files are present in the current directory

count=1
filenames="bashout"
dir="testout"

mkdir -p $dir

for count in 1 2 3 4 5 6 7 8 9 10
do
	echo test/"test"$count".txt"
	./Underscorify test/"test"$count".txt"
done

./Underscorify main.cpp
g++ -o Underscorifyout mainout.cpp

for count in 1 2 3 4 5 6 7 8 9 10
do
	echo test/out/"test"$count".txt"
	./Underscorifyout test/out/"test"$count".txt"
done

for count in 1 2 3 4 5 6 7 8 9 10
do
	echo "diff between test/out/test"$count"out.txt and test/test"$count"out.txt"
	diff "test/out/test"$count"out.txt" "test/test"$count"out.txt"
done