#define _ using
#define __ namespace
#define ___ std
#define ____ ;
#define _____ int
#define ______ main
#define _______ (
#define ________ )
#define _________ {
#define __________ }
#define ___________ cout
#define ____________ <<
#define _____________ endl
#define ______________ return
#define _______________ 0